### ISSUE TITLE
Move / copy this repo to open-watcom.github.io repo

### ISSUE THREAD

**Issue by jayschwa** [open-watcom/open-watcom.github.io#2]
https://open-watcom.github.io/ is currently a 404 page. I think it would make sense to host content from the bare domain and not require the additional and redundant `/open-watcom` after the domain name.

https://pages.github.com/ has more information.

**Comment by jmalak** [comment]
It is not necessary.
Rename functionality works OK.
Now renamed to open-watcom.github.io repository.

**Comment by jayschwa** [comment]
I suggest you check the repo settings to see which branch it is serving from. `gh-pages` branch may need to be copied to `master`.

**Comment by jmalak** [comment]
Thanks, I see.
I will do migration from old structure.

**Comment by jmalak** [comment]
I renamed branch and now it is working.
Thanks for your suggestion.
I will review used links and change where it is necessary.
